---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: todolist
  name: todolist
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - image: ${REPO}/java-goof:latest
        imagePullPolicy: Always
        name: todolist
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /usr/local/tomcat/temp
            name: tomcat-temp
          - mountPath: /usr/local/tomcat/work
            name: tomcat-work
          - mountPath: /usr/local/tomcat/logs
            name: tomcat-logs
      restartPolicy: Always
      volumes:
        - name: tomcat-temp
          emptyDir: {}
        - name: tomcat-work
          emptyDir: {}
        - name: tomcat-logs
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: todolist
  name: todolist
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: todolist
